# Generated by Django 5.0.1 on 2024-02-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='Length',
            new_name='length',
        ),
    ]
