# Generated by Django 5.0.1 on 2024-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_captain_alter_cleaning_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='captains',
            field=models.ManyToManyField(to='main_app.captain'),
        ),
        migrations.AlterField(
            model_name='captain',
            name='experience',
            field=models.IntegerField(verbose_name='Experience (Years)'),
        ),
    ]
